import { QuestionTemplateType } from "../projects-tracker/types";
import { QuestionData } from "./types";

export const initialQuestionsData: QuestionData[] = [
  // ─────────────────────────────────────────────────────────────
  // 1. EXISTING BUILDING
  // ─────────────────────────────────────────────────────────────
  {
    id: "Q1",
    sectionTitle: "Existing Building",
    category: "existing_building",
    questionText: "Type of construction (existing building)",
    questionType: QuestionTemplateType.Input,
    answer: "Type V",
    boolean_answer: null,
  },
  {
    id: "Q2",
    sectionTitle: "Existing Building",
    category: "existing_building",
    questionText: "Number of stories of occupancy (existing building)",
    questionType: QuestionTemplateType.Input,
    answer: "3",
    boolean_answer: null,
  },
  {
    id: "Q3",
    sectionTitle: "Existing Building",
    category: "existing_building",
    questionText: "Number of basements and cellars (existing building)",
    questionType: QuestionTemplateType.Input,
    answer: "1",
    boolean_answer: null,
  },
  {
    id: "Q4",
    sectionTitle: "Existing Building",
    category: "existing_building",
    questionText: "Present use (existing building)",
    questionType: QuestionTemplateType.Input,
    answer: "Retail",
    boolean_answer: null,
  },
  {
    id: "Q5",
    sectionTitle: "Existing Building",
    category: "existing_building",
    questionText: "Occupancy class (existing building)",
    questionType: QuestionTemplateType.Input,
    answer: "B",
    boolean_answer: null,
  },
  {
    id: "Q6",
    sectionTitle: "Existing Building",
    category: "existing_building",
    questionText: "Number of dwelling units (existing building)",
    questionType: QuestionTemplateType.Input,
    answer: "6",
    boolean_answer: null,
  },

  // ─────────────────────────────────────────────────────────────
  // 2. PROPOSED ALTERATION
  // ─────────────────────────────────────────────────────────────
  {
    id: "Q7",
    sectionTitle: "Proposed Alteration",
    category: "proposed_alteration",
    questionText: "Type of construction (after proposed alteration)",
    questionType: QuestionTemplateType.Input,
    answer: "Type V-A",
    boolean_answer: null,
  },
  {
    id: "Q8",
    sectionTitle: "Proposed Alteration",
    category: "proposed_alteration",
    questionText: "Number of stories of occupancy (after proposed alteration)",
    questionType: QuestionTemplateType.Input,
    answer: "4",
    boolean_answer: null,
  },
  {
    id: "Q9",
    sectionTitle: "Proposed Alteration",
    category: "proposed_alteration",
    questionText: "Number of basements and cellars (after proposed alteration)",
    questionType: QuestionTemplateType.Input,
    answer: "2",
    boolean_answer: null,
  },
  {
    id: "Q10",
    sectionTitle: "Proposed Alteration",
    category: "proposed_alteration",
    questionText: "Proposed use (legal use)",
    questionType: QuestionTemplateType.Input,
    answer: "Office",
    boolean_answer: null,
  },
  {
    id: "Q11",
    sectionTitle: "Proposed Alteration",
    category: "proposed_alteration",
    questionText: "Occupancy class (after proposed alteration)",
    questionType: QuestionTemplateType.Input,
    answer: "A-2",
    boolean_answer: null,
  },
  {
    id: "Q12",
    sectionTitle: "Proposed Alteration",
    category: "proposed_alteration",
    questionText: "Number of dwelling units (after proposed alteration)",
    questionType: QuestionTemplateType.Input,
    answer: "8",
    boolean_answer: null,
  },
  {
    id: "Q13",
    sectionTitle: "Proposed Alteration",
    category: "proposed_alteration",
    questionText: "Does this alteration create additional height or story?",
    questionType: QuestionTemplateType.Boolean,
    answer: null,
    boolean_answer: true,
  },
  {
    id: "Q14",
    sectionTitle: "Proposed Alteration",
    category: "proposed_alteration",
    questionText: "New height at center line of front (if height added)",
    questionType: QuestionTemplateType.Input,
    answer: "55 ft",
    boolean_answer: null,
  },
  {
    id: "Q15",
    sectionTitle: "Proposed Alteration",
    category: "proposed_alteration",
    questionText: "Does this alteration create deck or horizontal extension?",
    questionType: QuestionTemplateType.Boolean,
    answer: null,
    boolean_answer: false,
  },
  {
    id: "Q16",
    sectionTitle: "Proposed Alteration",
    category: "proposed_alteration",
    questionText: "New ground floor area (sq ft) (if deck/extension)",
    questionType: QuestionTemplateType.Input,
    answer: "400",
    boolean_answer: null,
  },
  {
    id: "Q17",
    sectionTitle: "Proposed Alteration",
    category: "proposed_alteration",
    questionText: "Will sidewalk over sub-sidewalk space be repaired or altered?",
    questionType: QuestionTemplateType.Boolean,
    answer: null,
    boolean_answer: false,
  },
  {
    id: "Q18",
    sectionTitle: "Proposed Alteration",
    category: "proposed_alteration",
    questionText: "Will building extend beyond property line?",
    questionType: QuestionTemplateType.Boolean,
    answer: null,
    boolean_answer: false,
  },
  {
    id: "Q19",
    sectionTitle: "Proposed Alteration",
    category: "proposed_alteration",
    questionText: "Any other existing building on lot?",
    questionType: QuestionTemplateType.Boolean,
    answer: null,
    boolean_answer: true,
  },
  {
    id: "Q20",
    sectionTitle: "Proposed Alteration",
    category: "proposed_alteration",
    questionText: "Does this alteration constitute a change of occupancy?",
    questionType: QuestionTemplateType.Boolean,
    answer: null,
    boolean_answer: true,
  },

  // ─────────────────────────────────────────────────────────────
  // 3. SCOPE OF WORK
  // ─────────────────────────────────────────────────────────────
  {
    id: "Q21",
    sectionTitle: "Scope of Work",
    category: "scope_of_work",
    questionText: "Description of all work to be performed",
    questionType: QuestionTemplateType.TextField,
    answer: "Tenant improvement and seismic retrofit",
    boolean_answer: null,
  },
  {
    id: "Q22",
    sectionTitle: "Scope of Work",
    category: "scope_of_work",
    questionText: "Is auto runway to be constructed or altered?",
    questionType: QuestionTemplateType.Boolean,
    answer: null,
    boolean_answer: false,
  },
  {
    id: "Q23",
    sectionTitle: "Scope of Work",
    category: "scope_of_work",
    questionText: "Will street space be used during construction?",
    questionType: QuestionTemplateType.Boolean,
    answer: null,
    boolean_answer: true,
  },
  {
    id: "Q24",
    sectionTitle: "Scope of Work",
    category: "scope_of_work",
    questionText: "Electrical work to be performed?",
    questionType: QuestionTemplateType.Boolean,
    answer: null,
    boolean_answer: true,
  },
  {
    id: "Q25",
    sectionTitle: "Scope of Work",
    category: "scope_of_work",
    questionText: "Plumbing work to be performed?",
    questionType: QuestionTemplateType.Boolean,
    answer: null,
    boolean_answer: false,
  },

  // ─────────────────────────────────────────────────────────────
  // 4. CONTRACTOR INFORMATION
  // ─────────────────────────────────────────────────────────────
  {
    id: "Q26",
    sectionTitle: "Contractor Information",
    category: "contractor_information",
    questionText: "Contractor name",
    questionType: QuestionTemplateType.Input,
    answer: "ABC Construction Co.",
    boolean_answer: null,
  },
  {
    id: "Q27",
    sectionTitle: "Contractor Information",
    category: "contractor_information",
    questionText: "Contractor address",
    questionType: QuestionTemplateType.Input,
    answer: "123 Market Street",
    boolean_answer: null,
  },
  {
    id: "Q28",
    sectionTitle: "Contractor Information",
    category: "contractor_information",
    questionText: "Contractor ZIP",
    questionType: QuestionTemplateType.Input,
    answer: "94103",
    boolean_answer: null,
  },
  {
    id: "Q29",
    sectionTitle: "Contractor Information",
    category: "contractor_information",
    questionText: "Contractor phone",
    questionType: QuestionTemplateType.Input,
    answer: "415-555-7890",
    boolean_answer: null,
  },
  {
    id: "Q30",
    sectionTitle: "Contractor Information",
    category: "contractor_information",
    questionText: "Contractor California license number",
    questionType: QuestionTemplateType.Input,
    answer: "C1234567",
    boolean_answer: null,
  },
  {
    id: "Q31",
    sectionTitle: "Contractor Information",
    category: "contractor_information",
    questionText: "Contractor license expiration date",
    questionType: QuestionTemplateType.Input,
    answer: "2025-12-31",
    boolean_answer: null,
  },

  // ─────────────────────────────────────────────────────────────
  // 5. OWNER INFORMATION
  // ─────────────────────────────────────────────────────────────
  {
    id: "Q32",
    sectionTitle: "Owner Information",
    category: "owner_information",
    questionText: "Owner/Lessee name",
    questionType: QuestionTemplateType.Input,
    answer: "John Doe",
    boolean_answer: null,
  },
  {
    id: "Q33",
    sectionTitle: "Owner Information",
    category: "owner_information",
    questionText: "Owner/Lessee address",
    questionType: QuestionTemplateType.Input,
    answer: "456 Mission Street",
    boolean_answer: null,
  },
  {
    id: "Q34",
    sectionTitle: "Owner Information",
    category: "owner_information",
    questionText: "Owner/Lessee ZIP",
    questionType: QuestionTemplateType.Input,
    answer: "94105",
    boolean_answer: null,
  },
  {
    id: "Q35",
    sectionTitle: "Owner Information",
    category: "owner_information",
    questionText: "Owner/Lessee BTRC number",
    questionType: QuestionTemplateType.Input,
    answer: "BTRC12345",
    boolean_answer: null,
  },
  {
    id: "Q36",
    sectionTitle: "Owner Information",
    category: "owner_information",
    questionText: "Owner/Lessee phone",
    questionType: QuestionTemplateType.Input,
    answer: "415-555-1234",
    boolean_answer: null,
  },

  // ─────────────────────────────────────────────────────────────
  // 6. ARCHITECT INFORMATION
  // ─────────────────────────────────────────────────────────────
  {
    id: "Q37",
    sectionTitle: "Architect Information",
    category: "architect_information",
    questionText: "Architect or engineer name",
    questionType: QuestionTemplateType.Input,
    answer: "Jane Smith",
    boolean_answer: null,
  },
  {
    id: "Q38",
    sectionTitle: "Architect Information",
    category: "architect_information",
    questionText: "Architect/Engineer role",
    questionType: QuestionTemplateType.SelectOne,
    answer: "Design",
    boolean_answer: null,
  },
  {
    id: "Q39",
    sectionTitle: "Architect Information",
    category: "architect_information",
    questionText: "Architect/Engineer address",
    questionType: QuestionTemplateType.Input,
    answer: "789 Pine Street",
    boolean_answer: null,
  },
  {
    id: "Q40",
    sectionTitle: "Architect Information",
    category: "architect_information",
    questionText: "Architect/Engineer California certificate number",
    questionType: QuestionTemplateType.Input,
    answer: "ARCH56789",
    boolean_answer: null,
  },

  // ─────────────────────────────────────────────────────────────
  // 7. ADDITIONAL INFORMATION
  // ─────────────────────────────────────────────────────────────
  {
    id: "Q41",
    sectionTitle: "Additional Info",
    category: "additional_info",
    questionText: 'Construction lender name or "Unknown"',
    questionType: QuestionTemplateType.Input,
    answer: "Bank of SF",
    boolean_answer: null,
  },
];
